/* Diccionario INGLÉS. Traduce la cabecera y las tarjetas. Lo que falte cae al español. */
registrarIdioma('en', {
  'ajustes.tituloApp': 'Application settings',
  'ajustes.subApp': 'What applies to the whole application.',

  // --- per-section cards ---
  'ajustes.calendario': 'Calendar',
  'ajustes.calendario.d': 'Hours, events and dates.',
  'ajustes.ramos': 'Courses',
  'ajustes.ramos.d': 'Assessments and courses.',
  'ajustes.tareas': 'Tasks',
  'ajustes.tareas.d': 'To-dos and commitments.',
  'ajustes.estudio': 'Study',
  'ajustes.estudio.d': 'Study time log.',
  'ajustes.malla': 'Curriculum',
  'ajustes.malla.d': 'Degree courses.',
  'ajustes.tiempo': 'Time',
  'ajustes.tiempo.d': 'Stopwatches, timer and more.',
  // --- the Time section panel ---
  'ajustes.avisos': 'Alerts when it ends',
  'ajustes.avisos.d': 'It rings and shows an on-screen alert when the timer reaches zero.',
  'ajustes.si': 'Yes',
  'ajustes.no': 'No',
  'ajustes.notificar': 'System notification',
  'ajustes.notificar.d': 'A system alert even while you look at another window.',
  'ajustes.notif.activar': 'Turn on',
  'ajustes.notif.explica': 'Press “Turn on” and the system will ask for permission once.',
  'ajustes.notif.concedido': 'On: the system already alerts you.',
  'ajustes.notif.denegado': 'Blocked in the system permissions. Enable it there to use it.',
  'ajustes.notif.nosoporte': 'This system does not allow notifications.',
  'ajustes.timbre': 'Ringtone',
  'ajustes.timbre.d': 'The Mimo alarm, a device beep, or your own audio file.',
  'tiempo.son.propia': 'Mimo alarm',
  'tiempo.son.pitido': 'Device beep',
  'tiempo.son.archivo': 'Own file',
  'tiempo.sin.archivo': 'No file chosen',
  'tiempo.archivo.tu': 'Your ringtone (an audio file)',
  'tiempo.timbre.titulo': 'Choose an audio file',
  'tiempo.formato.nota': 'The time format is global: it is changed in “General”, and applies to every section.',

  // --- application cards ---
  'ajustes.apariencia': 'Appearance',
  'ajustes.apariencia.d': 'Theme and colour.',
  'ajustes.general': 'General',
  'ajustes.general.d': 'What applies to the whole application.',
  'ajustes.navegacion': 'Navigation',
  'ajustes.navegacion.d': 'Where the sections sit and how you move between them.',
  'ajustes.idioma': 'Language',
  'ajustes.idioma.d': 'The language of the interface.',
  'ajustes.colaborar': 'Support us',
  'ajustes.colaborar.d': 'Three ways to help without paying; the coffee is optional.',
  'ajustes.semestre': 'Term',
  'ajustes.semestre.d': 'Saved terms and their goals.',
  'ajustes.respaldo': 'Backup',
  'ajustes.respaldo.d': 'Your data lives on this device: this is what keeps it safe. Download it, load it on another device, or start over.',
  'ajustes.respaldo.pendiente': 'pending',
  'ajustes.respaldo.sync': 'synced to {ruta}',
  'ajustes.respaldoTilde': 'the most important',

  // --- the Language panel ---
  'idioma.sub': 'The language of the interface texts.',
  'idioma.titulo': 'Interface language',
  'idioma.nota': 'Eight languages. Only the finished ones translate for real; the rest stay in Spanish.',
  'idioma.preparacion': 'in preparation',
  'idioma.simplificado': 'Simplified Chinese',
  'idioma.tradicional': 'Traditional Chinese',

  // --- the Support window (GitHub ONLY; no email address is published here) ---
  'colab.intro': { parts: [
    'Mimo is ', ['b', 'free and ad-free'],
    '. If it is useful to you, you can help like this (everything opens on GitHub):'
  ] },
  'colab.fallo': 'Report a bug',
  'colab.fallo.d': 'Something that does not work or looks wrong.',
  'colab.idea': 'Suggest an idea',
  'colab.idea.d': 'Something that is missing or could be better.',
  'colab.compartir': 'Tell someone about it',
  'colab.compartir.d': 'A classmate who could use it.',
  'colab.compartir.titulo': 'Mimo Academics',
  'colab.cafe': 'Buy me a coffee',
  'colab.cafe.nota': 'Optional; the app charges nothing inside.',
  'colab.copiado': 'Link copied.',
  'colab.faq': 'Frequently asked questions',
  'colab.faq.cuenta': 'five usual doubts, answered',
  'colab.p1': 'Do I have to support it?',
  'colab.r1': 'No. Mimo works just as fully without supporting it.',
  'colab.p2': 'Do I need a GitHub account?',
  'colab.r2': 'Only to report a bug or suggest an idea: GitHub asks for an account to post (it is free). To share the app, you do not need one.',
  'colab.p3': 'Will my data be visible if I report?',
  'colab.r3': 'No. The report only carries the Mimo version and your system; never your courses, notes or backup. If you add a screenshot, cover your own data first.',
  'colab.p4': 'Where does what you contribute go?',
  'colab.r4': 'To keeping the project alive: the time of whoever makes it and what it costs to keep it online.',
  'colab.p5': 'Can I help in another way?',
  'colab.r5': 'Yes: the three above help as much or more than the coffee.',
  'colab.fallo.cuerpo': 'What happened:\n\n\nWhat you expected to happen:\n\n\nHow to reproduce it:\n1. \n2. \n3. \n\n— Device details (filled in for you) —\nMimo version: {version}\nSystem: {sistema}\n\nIf you add screenshots, cover your own data first.',

  // --- the Import window (Plan) ---
  'malla.importar.titulo': 'Import',
  'malla.importar.sub': 'JSON, CSV, TSV or PDF',
  'malla.importar.campo': 'File',
  'malla.importar.elegir': 'Choose file',
  'malla.importar.ninguno': 'No file chosen',
  'malla.importar.ayuda': 'A PDF of your plan, or a JSON, CSV or TSV file.',
  'malla.importar.pegar': 'Paste the courses you see here, one per line',

  // --- window buttons ---
  'boton.cancelar': 'Cancel',
  'boton.importar': 'Import',
  'boton.cerrar': 'Close'
});
